package com.jonathan.backend.entidades;

// default package
// Generated 23 mar 2025, 19:34:28 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Citas generated by hbm2java
 */
@Entity
@Table(name = "citas", catalog = "garagebox")
public class Citas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idCita;
	private Usuarios usuarios;
	private Vehiculos vehiculos;
	private Date fechaHora;
	private String descripcion;
	private String estado;
	private Date fechaCreacion = new Date();
	private Conversaciones conversacion;
	private Set<Facturas> facturases = new HashSet<Facturas>(0);
	private Set<MecanicosCitas> mecanicosCitases = new HashSet<MecanicosCitas>(0);
	private Set<Seguimiento> seguimientos = new HashSet<Seguimiento>(0);

	public Citas() {
	}

	public Citas(Long idCita, Date fechaHora) {
		this.idCita = idCita;
		this.fechaHora = fechaHora;
	}

	public Citas(Long idCita, Usuarios usuarios, Vehiculos vehiculos, Date fechaHora, String descripcion, String estado,
			Date fechaCreacion, Set<Facturas> facturases, Set<MecanicosCitas> mecanicosCitases, Set<Seguimiento> seguimientos) {
		this.idCita = idCita;
		this.usuarios = usuarios;
		this.vehiculos = vehiculos;
		this.fechaHora = fechaHora;
		this.descripcion = descripcion;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.facturases = facturases;
		this.mecanicosCitases = mecanicosCitases;
		this.seguimientos = seguimientos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_cita", unique = true, nullable = false)
	public Long getIdCita() {
		return this.idCita;
	}

	public void setIdCita(Long idCita) {
		this.idCita = idCita;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	@JsonBackReference("usuario-cita")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_vehiculo")
	@JsonBackReference("vehiculo-cita")
	public Vehiculos getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Vehiculos vehiculos) {
		this.vehiculos = vehiculos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora", nullable = true, length = 29)
	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estado", length = 50)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion",nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "citas")
	public Set<Facturas> getFacturases() {
		return this.facturases;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_conversacion")
	public Conversaciones getConversacion() {
	    return conversacion;
	}

	public void setConversacion(Conversaciones conversacion) {
	    this.conversacion = conversacion;
	}

	public void setFacturases(Set<Facturas> facturases) {
		this.facturases = facturases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "citas")
	public Set<MecanicosCitas> getMecanicosCitases() {
		return this.mecanicosCitases;
	}

	public void setMecanicosCitases(Set<MecanicosCitas> mecanicosCitases) {
		this.mecanicosCitases = mecanicosCitases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "citas")
	@JsonBackReference("cita-seguimiento")
	public Set<Seguimiento> getSeguimientos() {
		return this.seguimientos;
	}

	public void setSeguimientos(Set<Seguimiento> seguimientos) {
		this.seguimientos = seguimientos;
	}

}
