package com.jonathan.backend.entidades;

// default package
// Generated 23 mar 2025, 19:34:28 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Facturas generated by hbm2java
 */
@Entity
@Table(name = "facturas", catalog = "garagebox")
public class Facturas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idFactura;
	private Citas citas;
	private BigDecimal montoTotal;
	private Date fechaEmision;
	private String estadoPago;

	public Facturas() {
	}

	public Facturas(Long idFactura, BigDecimal montoTotal) {
		this.idFactura = idFactura;
		this.montoTotal = montoTotal;
	}

	public Facturas(Long idFactura, Citas citas, BigDecimal montoTotal, Date fechaEmision, String estadoPago) {
		this.idFactura = idFactura;
		this.citas = citas;
		this.montoTotal = montoTotal;
		this.fechaEmision = fechaEmision;
		this.estadoPago = estadoPago;
	}

	@Id
	@GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY)
	@Column(name = "id_factura", unique = true, nullable = false)
	public Long getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(Long idFactura) {
		this.idFactura = idFactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cita")
	public Citas getCitas() {
		return this.citas;
	}

	public void setCitas(Citas citas) {
		this.citas = citas;
	}

	@Column(name = "monto_total", nullable = false, precision = 10)
	public BigDecimal getMontoTotal() {
		return this.montoTotal;
	}

	public void setMontoTotal(BigDecimal montoTotal) {
		this.montoTotal = montoTotal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_emision", length = 29)
	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	@Column(name = "estado_pago", length = 50)
	public String getEstadoPago() {
		return this.estadoPago;
	}

	public void setEstadoPago(String estadoPago) {
		this.estadoPago = estadoPago;
	}

}
