package com.jonathan.backend.entidades;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * MecanicosCitas generated by hbm2java
 */
@Entity
@Table(name = "mecanicos_citas", catalog = "garagebox")
public class MecanicosCitas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MecanicosCitasId id;
	private Citas citas;
	private Usuarios usuarios;

	public MecanicosCitas() {
	}

	public MecanicosCitas(MecanicosCitasId id, Citas citas, Usuarios usuarios) {
		this.id = id;
		this.citas = citas;
		this.usuarios = usuarios;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idMecanico", column = @Column(name = "id_mecanico", nullable = false)),
			@AttributeOverride(name = "idCita", column = @Column(name = "id_cita", nullable = false)) })
	public MecanicosCitasId getId() {
		return this.id;
	}

	public void setId(MecanicosCitasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cita", nullable = false, insertable = false, updatable = false)
	public Citas getCitas() {
		return this.citas;
	}

	public void setCitas(Citas citas) {
		this.citas = citas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_mecanico", nullable = false, insertable = false, updatable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
