package com.jonathan.backend.entidades;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import java.io.Serializable;
import java.util.Objects;

/**
 * MecanicosCitasId generated by hbm2java
 */
@Embeddable
public class MecanicosCitasId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Long idMecanico;
    private Long idCita;

    public MecanicosCitasId() {}

    public MecanicosCitasId(Long idMecanico, Long idCita) {
        this.idMecanico = idMecanico;
        this.idCita = idCita;
    }

    @Column(name = "id_mecanico", nullable = false)
    public Long getIdMecanico() {
        return this.idMecanico;
    }

    public void setIdMecanico(Long idMecanico) {
        this.idMecanico = idMecanico;
    }

    @Column(name = "id_cita", nullable = false)
    public Long getIdCita() {
        return this.idCita;
    }

    public void setIdCita(Long idCita) {
        this.idCita = idCita;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        if (!(other instanceof MecanicosCitasId)) return false;
        MecanicosCitasId that = (MecanicosCitasId) other;
        return Objects.equals(idMecanico, that.idMecanico) &&
               Objects.equals(idCita, that.idCita);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idMecanico, idCita);
    }
}