package com.jonathan.backend.entidades;

// default package
// Generated 23 mar 2025, 19:34:28 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Mensajes generated by hbm2java
 */
@Entity
@Table(name = "mensajes", catalog = "garagebox")
public class Mensajes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idMensaje;
	private Conversaciones conversaciones;
	private Usuarios usuarios;
	private String contenido;
	private Date fechaEnvio;
	private Boolean leido;

	public Mensajes() {
	}

	public Mensajes(Long idMensaje, String contenido) {
		this.idMensaje = idMensaje;
		this.contenido = contenido;
	}

	public Mensajes(Long idMensaje, Conversaciones conversaciones, Usuarios usuarios, String contenido, Date fechaEnvio,
			Boolean leido) {
		this.idMensaje = idMensaje;
		this.conversaciones = conversaciones;
		this.usuarios = usuarios;
		this.contenido = contenido;
		this.fechaEnvio = fechaEnvio;
		this.leido = leido;
	}

	@Id
	@GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY)
	@Column(name = "id_mensaje", unique = true, nullable = false)
	public Long getIdMensaje() {
		return this.idMensaje;
	}

	public void setIdMensaje(Long idMensaje) {
		this.idMensaje = idMensaje;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_conversacion")
	public Conversaciones getConversaciones() {
		return this.conversaciones;
	}

	public void setConversaciones(Conversaciones conversaciones) {
		this.conversaciones = conversaciones;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_remitente")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "contenido", nullable = false)
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_envio", length = 29)
	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	@Column(name = "leido")
	public Boolean getLeido() {
		return this.leido;
	}

	public void setLeido(Boolean leido) {
		this.leido = leido;
	}

}
