package com.jonathan.backend.entidades;

// default package
// Generated 23 mar 2025, 19:34:28 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Seguimiento generated by hbm2java
 */
@Entity
@Table(name = "seguimiento", catalog = "garagebox")
public class Seguimiento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idSeguimiento;
	private Citas citas;
	private String descripcion;
	private String imagenUrl;
	private String estado;
	private Date fechaActualizacion;

	public Seguimiento() {
	}

	public Seguimiento(Long idSeguimiento, String descripcion) {
		this.idSeguimiento = idSeguimiento;
		this.descripcion = descripcion;
	}

	public Seguimiento(Long idSeguimiento, Citas citas, String descripcion, String imagenUrl, String estado,
			Date fechaActualizacion) {
		this.idSeguimiento = idSeguimiento;
		this.citas = citas;
		this.descripcion = descripcion;
		this.imagenUrl = imagenUrl;
		this.estado = estado;
		this.fechaActualizacion = fechaActualizacion;
	}

	@Id
	@GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY)
	@Column(name = "id_seguimiento", unique = true, nullable = false)
	public Long getIdSeguimiento() {
		return this.idSeguimiento;
	}

	public void setIdSeguimiento(Long idSeguimiento) {
		this.idSeguimiento = idSeguimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cita")
	@JsonBackReference("cita-seguimiento")
	public Citas getCitas() {
		return this.citas;
	}

	public void setCitas(Citas citas) {
		this.citas = citas;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "imagen_url")
	public String getImagenUrl() {
		return this.imagenUrl;
	}

	public void setImagenUrl(String imagenUrl) {
		this.imagenUrl = imagenUrl;
	}

	@Column(name = "estado", length = 50)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_actualizacion", length = 29)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

}
