package com.jonathan.backend.entidades;

// default package
// Generated 23 mar 2025, 19:34:28 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Vehiculos generated by hbm2java
 */
@Entity
@Table(name = "vehiculos", catalog = "garagebox", uniqueConstraints = @UniqueConstraint(columnNames = "matricula"))
public class Vehiculos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idVehiculo;
	private Usuarios usuarios;
	private String marca;
	private String modelo;
	private String matricula;
	private Integer anoFabricacion;
	private String tipoMotor;
	private Set<Citas> citases = new HashSet<Citas>(0);

	public Vehiculos() {
	}

	public Vehiculos(Long idVehiculo, String marca, String modelo, String matricula) {
		this.idVehiculo = idVehiculo;
		this.marca = marca;
		this.modelo = modelo;
		this.matricula = matricula;
	}

	public Vehiculos(Long idVehiculo, Usuarios usuarios, String marca, String modelo, String matricula,
			Integer anoFabricacion, String tipoMotor, Set<Citas> citases) {
		this.idVehiculo = idVehiculo;
		this.usuarios = usuarios;
		this.marca = marca;
		this.modelo = modelo;
		this.matricula = matricula;
		this.anoFabricacion = anoFabricacion;
		this.tipoMotor = tipoMotor;
		this.citases = citases;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_vehiculo", unique = true, nullable = false)
	public Long getIdVehiculo() {
		return this.idVehiculo;
	}

	public void setIdVehiculo(Long idVehiculo) {
		this.idVehiculo = idVehiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	@JsonBackReference("usuario-vehiculo")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "marca", nullable = false, length = 50)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "modelo", nullable = false, length = 50)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "matricula", unique = true, nullable = false, length = 20)
	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	@Column(name = "ano_fabricacion")
	public Integer getAnoFabricacion() {
		return this.anoFabricacion;
	}

	public void setAnoFabricacion(Integer anoFabricacion) {
		this.anoFabricacion = anoFabricacion;
	}

	@Column(name = "tipo_motor", length = 50)
	public String getTipoMotor() {
		return this.tipoMotor;
	}

	public void setTipoMotor(String tipoMotor) {
		this.tipoMotor = tipoMotor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculos")
	@JsonManagedReference("vehiculo-cita")
	public Set<Citas> getCitases() {
		return this.citases;
	}

	public void setCitases(Set<Citas> citases) {
		this.citases = citases;
	}

}
